---
roles:
  - name: geerlingguy.git
  - name: geerlingguy.docker
  - name: geerlingguy.filebeat
  - name: geerlingguy.repo-epel
  - name: dev-sec.ssh-hardening
  - name: robertdebock.selinux
  - name: dj-wasabi.telegraf
