---
roles:
  - name: dj-wasabi.telegraf
    version: 0.13.0
  - name: elastic.beats
    version: v7.10.2
  - name: geerlingguy.git
    version: 3.0.0
  - name: geerlingguy.repo-epel
    version: 3.0.0

collections:
  - name: devsec.hardening
    version: 7.0.0
