---
- hosts: all
  gather_facts: false

  tasks:

    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_secret_lookup.html
    - name: secrets manager secret create
      community.aws.aws_secret:
        name: 'somesecretsecretsmanager'
        state: present
        secret_type: 'string'
        secret: "
                somesecretsmanagerkey\n
                line2
                "
        region: 'us-east-1'

    - name: secrets manager secret print
      copy:
        mode: 0755
        dest: /tmp/some_file_secretsmanager
        content: |
          {{ lookup('amazon.aws.aws_secret', 'somesecretsecretsmanager', nested=false, region='us-east-1') }}

    - name: secrets manager secret remove
      community.aws.aws_secret:
        name: 'somesecretsecretsmanager'
        state: absent
        secret_type: 'string'
        secret: "somesecretsecretsmanager"
        region: 'us-east-1'
        recovery_window: 0
