---
- hosts: all
  tasks:

  collections:
    - devsec.hardening

  roles:
    - devsec.hardening.ssh_hardening
    - devsec.hardening.os_hardening
    - elastic.beats
    - dj-wasabi.telegraf

- name: iptables
  import_playbook: iptables.yaml

  vars:
    beats_version: 7.12.0
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log
    telegraf_agent_package_state: latest
