---
- hosts: all
  tasks:

  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.ssh_hardening
    - devsec.hardening.os_hardening
    - elastic.beats
    - geerlingguy.repo-epel
    - dj-wasabi.telegraf
  vars:
    beats_version: 7.10.2
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log
