---
- hosts: all
  tasks:

  # galaxy roles
  - name: ssh
    import_role:
      name: dev-sec.ssh-hardening
  - name: telegraf
    import_role:
      name: dj-wasabi.telegraf
  - name: selinux
    import_role:
      name: dev-sec.os-hardening
  - name: epel
    import_role:
      name: geerlingguy.repo-epel
  - name: filebeat
    import_role:
      name: geerlingguy.filebeat
