---
- import_playbook: base.yaml

- hosts: all

  vars_prompt:

    - name: vault_token
      prompt: What is the vault token?
      private: "yes"
      default: root

    - name: vault_server
      prompt: What is the vault server?
      private: "no"
      default: localhost

  tasks:
    - import_role:
       name: roles/test
